# Generated by Django 4.1.4 on 2022-12-20 17:20

from django.db import migrations, models
import django.db.models.deletion
import expenses.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0002_alter_vehicle_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                (
                    "vendor",
                    models.CharField(blank=True, max_length=128, verbose_name="vendor"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("repair", "Repair"),
                            ("administrative", "Administrative"),
                            ("various", "Various"),
                        ],
                        default="maintenance",
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "mileage",
                    models.IntegerField(blank=True, null=True, verbose_name="mileage"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to=expenses.models.upload_doc,
                        verbose_name="file",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "expense",
                "ordering": ["-date"],
            },
        ),
    ]
