# Generated by Django 4.1.5 on 2023-01-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_currency_appsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "app setting"},
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.currency",
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="distance_unit",
            field=models.CharField(
                choices=[("Km", "kilometers"), ("Mi", "miles")],
                default="Km",
                max_length=24,
                verbose_name="distance unit",
            ),
        ),
        migrations.DeleteModel(
            name="AppSettings",
        ),
    ]
