# Generated by Django 4.1.4 on 2022-12-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="description"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="manufacturer"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=64, verbose_name="model"),
                ),
                (
                    "horsepower",
                    models.IntegerField(default=0, verbose_name="horsepower"),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "diesel"),
                            ("petrol", "petrol"),
                            ("ethanol", "ethanol"),
                            ("electric", "electric"),
                            ("cng", "CNG"),
                            ("lpg", "LPG"),
                        ],
                        default="diesel",
                        max_length=32,
                        verbose_name="fuel type",
                    ),
                ),
                (
                    "fuel_unit",
                    models.CharField(
                        choices=[
                            ("L", "liter"),
                            ("gal", "gallon"),
                            ("kg", "kilogram"),
                            ("KWh", "kilowatt hour"),
                            ("min", "minutes"),
                        ],
                        default="L",
                        max_length=32,
                        verbose_name="fuel unit",
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(blank=True, null=True, verbose_name="mileage"),
                ),
                ("tank_size", models.IntegerField(default=0, verbose_name="tank size")),
                (
                    "date_first_registration",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of 1st circulation"
                    ),
                ),
                (
                    "registration",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="registration",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="price",
                    ),
                ),
                (
                    "date_purchase",
                    models.DateField(
                        blank=True, null=True, verbose_name="date purchase"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=vehicles.models.upload_img,
                        verbose_name="picture",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "inactive_since",
                    models.DateField(
                        blank=True, null=True, verbose_name="inactive since"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="owner_vehicle"
            ),
        ),
    ]
