# Generated by Django 4.1.4 on 2022-12-19 16:41

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="picture",
            field=private_storage.fields.PrivateImageField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=vehicles.models.upload_img,
                verbose_name="picture",
            ),
        ),
    ]
