# Generated by Django 4.1.4 on 2022-12-22 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.IntegerField(default=0, verbose_name="mileage"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="price",
            ),
        ),
    ]
